[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = ["@self/contracts/=lib/self/contracts/contracts/"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
